formatting

diff --git a/.github/workflows/reusable_tests.yml b/.github/workflows/reusable_tests.yml
--- a/.github/workflows/reusable_tests.yml
+++ b/.github/workflows/reusable_tests.yml
@@ -1,4 +1,3 @@
-
 name: reusable tests
 
 on:
@@ -8,7 +7,7 @@ jobs:
   tests:
     strategy:
       matrix:
-        python: ['3.8', '3.9', '3.10', '3.11']
+        python: ["3.8", "3.9", "3.10", "3.11"]
         os: [ubuntu-latest, macos-latest, windows-latest]
 
     runs-on: ${{ matrix.os }}
@@ -28,7 +27,7 @@ jobs:
 
       - name: Print version
         run: .github/scripts/print_version.py
-        
+
       - name: Generate coverage report
         run: |
           pip install pytest pytest-cov coveralls
@@ -49,9 +48,9 @@ jobs:
     runs-on: ubuntu-latest
     container: python:3-slim
     steps:
-    - name: Finished
-      run: |
-        pip3 install --upgrade coveralls
-        coveralls --finish || echo "!! intermittent coveralls failure"
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Finished
+        run: |
+          pip3 install --upgrade coveralls
+          coveralls --finish || echo "!! intermittent coveralls failure"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
