add test, pyproject, version

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,1 +1,60 @@
 
+name: tests
+
+on:
+  push:
+    paths:
+      - "concurrentbuffer/**"
+      - "tests/**"
+      - .github/workflows/tests.yml
+  pull_request:
+    paths:
+      - "concurrentbuffer/**"
+      - "tests/**"
+      - .github/workflows/tests.yml
+
+env:
+  OS: ubuntu-latest
+  PYTHON_VERSION: "3.8"
+
+
+jobs:
+  tests:
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - name: Generate coverage report
+        run: |
+          pip install pytest pytest-cov coveralls
+          pytest tests tests --cov --cov-report term-missing
+      - name: Upload coverage
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          COVERALLS_PARALLEL: true
+        shell: bash
+        run: |
+          pip install coveralls
+          coveralls --service=github || echo "!! intermittent coveralls failure"
+  coveralls:
+    name: Indicate completion to coveralls.io
+    needs: tests
+    runs-on: ubuntu-latest
+    container: python:3-slim
+    steps:
+    - name: Finished
+      run: |
+        pip3 install --upgrade coveralls
+        coveralls --finish || echo "!! intermittent coveralls failure"
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
